import '../models/movie.dart';

var program = [
  Movie(
    name: 'Avatar', 
    picUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSaKZoi9-IkxLYjV6GB6tnoyrmoR1eySjfbm8NKkTb5Ig&s', 
    trailerUrl: 'https://www.youtube.com/watch?v=vKQi3bBA1y8', 
    rate: 7.5, 
    type: 'Action', 
    time: 120, 
    views: 1000, 
    cast: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'],
    description: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.', 
    showTime: [
      DateTime.now(), 
      DateTime.now().add(const Duration(hours: 3)),
      DateTime.now().add(const Duration(hours: 6)),
      DateTime.now().add(const Duration(days: 1)),
      DateTime.now().add(const Duration(days: 2)),
      DateTime.now().add(const Duration(days: 3)),
      DateTime.now().add(const Duration(days: 4)),
    ],
    price: 10
  ),
  Movie(
    name: 'Fast & Furious 9',
    picUrl: 'https://play-lh.googleusercontent.com/jxc2-6RFo8y6g1c0dcL-h35yZhGMQW8KABdG5VteDzNQJjvJvFvBsEkKQeC4mGQg2NfJlqiJrFHX7vJ05w',
    trailerUrl: 'https://www.youtube.com/watch?v=SKu3y0C5',
    rate: 7.4,
    type: 'Action',
    time: 145,
    views: 2000,
    cast: ['Vin Diesel', 'Michelle Rodriguez', 'Jordana Brewster'],
    description: 'Cipher enlists the help of Jakob, Dom\'s younger brother to take revenge on Dom and his team.',
    showTime: [DateTime.now(), DateTime.now().add(const Duration(hours: 3))],
    price: 10
  ),
  Movie(
    name: 'The Lord of the Rings: The Return of the King',
    picUrl: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTdaNx3DGiiQRu3fxzUhCRvp3O0k24PZX303HvygeRFABjMR8lF4_FyghoEcvEEw7mu0sFz',
    trailerUrl: 'https://www.youtube.com/watch?v=r5X-hFf6Bwo',
    rate: 8.9,
    type: 'Adventure',
    time: 201,
    views: 10000,
    cast: ['Elijah Wood', 'Viggo Mortensen', 'Ian McKellen'],
    description: 'Gandalf and Aragorn lead the World of Men against Sauron\'s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.',
    showTime: [DateTime.now(), DateTime.now().add(const Duration(hours: 3))],
    price: 22
  ),
  Movie(
    name: 'The Godfather: Part II',
    picUrl: 'https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpgD',
    trailerUrl: 'https://www.youtube.com/watch?v=2dN-IC8I6bM',
    rate: 9.0,
    type: 'Crime',
    time: 202,
    views: 8500,
    cast: ['Al Pacino', 'Robert De Niro', 'Robert Duvall'],
    description: 'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.',
    showTime: [DateTime.now(), DateTime.now().add(const Duration(hours: 3))],
    price: 21
  ),
  Movie(
    name: 'The Lord of the Rings: The Fellowship of the Ring',
    picUrl: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRGeRLWqh6Lsvp9q_iGaQ6Fxh5AKE8TfsjrXjvOt-Md-DnSipkFgMOWEMTbLkgk9FHMkCCFjQ',
    trailerUrl: 'https://www.youtube.com/watch?v=V75dMMIW2B4',
    rate: 8.8,
    type: 'Adventure',
    time: 178,
    views: 9500,
    cast: ['Elijah Wood', 'Ian McKellen', 'Orlando Bloom'],
    description: 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.',
    showTime: [DateTime.now(), DateTime.now().add(const Duration(hours: 3))],
    price: 20
  ),
  Movie(
    name: 'The Lord of the Rings: The Two Towers',
    picUrl: 'https://m.media-amazon.com/images/M/MV5BZGMxZTdjZmYtMmE2Ni00ZTdkLWI5NTgtNjlmMjBiNzU2MmI5XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_QL75_UX190_CR0,7,190,281_.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=LbfMDwc4azU',
    rate: 8.7,
    type: 'Adventure',
    time: 179,
    views: 9200,
    cast: ['Elijah Wood', 'Viggo Mortensen', 'Ian McKellen'],
    description: 'While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron\'s new ally, Saruman, and his hordes of Isengard.',
    showTime: [DateTime.now(), DateTime.now().add(const Duration(hours: 3))],
    price: 20
  ),
  Movie(
    name: 'The Dark Knight Rises',
    picUrl: 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQBEBjL_KIHOIKQZkRYhGHXMHrYhu5m4Sjhx-2-1QhOKGGZOleR2IT7xZ6zbcl_Plyrts4vjQ',
    trailerUrl: 'https://www.youtube.com/watch?v=g8evyE9TuYk',
    rate: 8.4,
    type: 'Action',
    time: 164,
    views: 7500,
    cast: ['Christian Bale', 'Tom Hardy', 'Anne Hathaway'],
    description: 'Eight years after the Joker\'s reign of anarchy, Batman, with the help of the enigmatic Catwoman, is forced from his exile to save Gotham City from the brutal guerrilla terrorist Bane.',
    showTime: [DateTime.now(), DateTime.now().add(const Duration(hours: 3))],
    price: 19
  ),
  Movie(
    name: 'The Matrix Reloaded',
    picUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMgVcIxoAOBSsoeYI9xpfac4D0RHl1tZGzgkNFhgm0o1gNUrRxs11sSJDdHZA2Ejc6mPtH',
    trailerUrl: 'https://www.youtube.com/watch?v=2_3o9a_N7Cc',
    rate: 7.2,
    type: 'Action',
    time: 138,
    views: 5000,
    cast: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'],
    description: 'Neo and the rebel leaders estimate that they have 72 hours until 250,000 probes discover Zion and destroy it and its inhabitants. During this, Neo must decide how he can save Trinity from a dark fate in his dreams.',
    showTime: [DateTime.now(), DateTime.now().add(const Duration(hours: 3))],
    price: 17
  ),
  Movie(
    name: 'Gladiator',
    picUrl: 'https://m.media-amazon.com/images/I/51GA6V6VE1L._AC_UF894,1000_QL80_.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=AxQajgTyLcM',
    rate: 8.5,
    type: 'Action',
    time: 155,
    views: 6000,
    cast: ['Russell Crowe', 'Joaquin Phoenix', 'Connie Nielsen'],
    description: 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
    showTime: [DateTime.now(), DateTime.now().add(const Duration(hours: 3))],
    price: 18
  ),
  Movie(
    name: 'The Departed',
    picUrl: 'https://play-lh.googleusercontent.com/yOtyaCoWJ2szPrVYTYpbCRAAI9Wov8kMADcxT0mW8wyoOHPYXFMghVwdoGAG1kxXIYBfJw',
    trailerUrl: 'https://www.youtube.com/watch?v=auYbpnEwBBg',
    rate: 8.5,
    type: 'Crime',
    time: 151,
    views: 5500,
    cast: ['Leonardo DiCaprio', 'Matt Damon', 'Jack Nicholson'],
    description: 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.',
    showTime: [DateTime.now(), DateTime.now().add(const Duration(hours: 3))],
    price: 18
  ),
  Movie(
    name: 'The Silence of the Lambs',
    picUrl: 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRoNJu9gYejdNIk3wUzmNfA80P-Y0VOKKE_CtxuytnvznUHQxpUfWgoUm5MBvU5kv3MWwx-Gw',
    trailerUrl: 'https://www.youtube.com/watch?v=lmrjOv0ufJ0',
    rate: 8.6,
    type: 'Crime',
    time: 118,
    views: 4500,
    cast: ['Jodie Foster', 'Anthony Hopkins', 'Lawrence A. Bonney'],
    description: 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.',
    showTime: [DateTime.now(), DateTime.now().add(const Duration(hours: 3))],
    price: 17
  ),
  Movie(
    name: 'Se7en',
    picUrl: 'https://m.media-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_QL75_UX190_CR0,8,190,281_.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=J4YV2_TcCoE',
    rate: 8.6,
    type: 'Crime',
    time: 127,
    views: 5500,
    cast: ['Morgan Freeman', 'Brad Pitt', 'Kevin Spacey'],
    description: 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.',
    showTime: [DateTime.now(), DateTime.now().add(const Duration(hours: 3))],
    price: 18
  ),
  Movie(
    name: 'The Usual Suspects',
    picUrl: 'https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p16422_p_v8_ag.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=oiXdPolca5w',
    rate: 8.5,
    type: 'Crime',
    time: 106,
    views: 5000,
    cast: ['Kevin Spacey', 'Gabriel Byrne', 'Chazz Palminteri'],
    description: 'A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.',
    showTime: [DateTime.now(), DateTime.now().add(const Duration(hours: 3))],
    price: 17
  ),
  Movie(
    name: 'Inglourious Basterds',
    picUrl: 'https://m.media-amazon.com/images/M/MV5BOTJiNDEzOWYtMTVjOC00ZjlmLWE0NGMtZmE1OWVmZDQ2OWJhXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_QL75_UX190_CR0,0,190,281_.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=KnrRy6kSFF0',
    rate: 8.3,
    type: 'Adventure',
    time: 153,
    views: 6000,
    cast: ['Brad Pitt', 'Diane Kruger', 'Eli Roth'],
    description: 'In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner\'s vengeful plans for the same.',
    showTime: [DateTime.now(), DateTime.now().add(const Duration(hours: 3))],
    price: 18
  ),
];